Update June 03, 2016; Now also checks for macs2 version

diff --git a/bin/checkPrerequisite b/bin/checkPrerequisite
--- a/bin/checkPrerequisite
+++ b/bin/checkPrerequisite
@@ -29,6 +29,15 @@ EOF
         echo
         exit 1
     fi
+
+    perl -M$1 -e 1
+
+    if [ $? -ne 0 ]; then
+        echo "Error: perl module $1 is missing."
+        echo "please install it using perl -MCPAN -e shell"
+        echo
+        exit 1
+    fi
 }
 
 check_r_module() {
